export const SET_CURRENT_STATE = "SET_CURRENT_STATE";
export const TOGGLE_PRECINCT_SWITCH = "TOGGLE_PRECINCT_SWITCH";
export const TOGGLE_DISTRICT_SWITCH = "TOGGLE_DISTRICT_SWITCH";
export const TOGGLE_ENACTED_SWITCH = "TOGGLE_ENACTED_SWITCH";
export const TOGGLE_COUNTY_SWITCH = "TOGGLE_COUNTY_SWITCH";
export const SET_TENTATIVE_DISTRICTING = "SET_TENTATIVE_DISTRICTING";
export const MOVE_MOUSE = "MOVE_MOUSE";
export const SET_MOUSE_ENTERED = "SET_MOUSE_ENTERED";
export const SET_FEATURED_DISTRICT = "SET_FEATURED_DISTRICT";
export const SET_FEATURED_PRECINCT = "SET_FEATURED_PRECINCT";
export const SET_MAP_REFERENCE = "SET_MAP_REFERENCE";
export const SET_LOADED_STATUS = "SET_LOADED_STATUS";
export const UPDATE_OBJECTIVE_FUNCTION_SETTINGS =
  "UPDATE_OBJECTIVE_FUNCTION_SETTINGS";
export const UPDATE_CONSTRAINT_SLIDER_SETTINGS =
  "UPDATE_CONSTRAINT_SLIDER_SETTINGS";
export const UPDATE_POPULATION_CONSTRAINT = "UPDATE_POPULATION_CONSTRAINT";
export const UPDATE_COMPACTNESS_CONSTRAINT = "UPDATE_COMPACTNESS_CONSTRAINT";
export const UPDATE_MINORITY_CONSTRAINT = "UPDATE_MINORITY_CONSTRAINT";
export const SET_IN_SELECTION_MENU = "SET_IN_SELECTION_MENU";
export const CHANGE_VALUE_SORTED_BY = "CHANGE_VALUE_SORTED_BY";
export const SET_COMPARISON_DISTRICTING_A = "SET_COMPARISON_DISTRICTING_A";
export const SET_COMPARISON_DISTRICTING_B = "SET_COMPARISON_DISTRICTING_B";
export const ADD_FEATURE_TO_HIGHLIGHT = "ADD_FEATURE_TO_HIGHLIGHT";
export const REMOVE_FEATURE_HIGHLIGHTING = "REMOVE_FEATURE_HIGHLIGHTING";
export const RESET_ALL_HIGHLIGHTING = "RESET_ALL_HIGHLIGHTING";
export const CLEAR_FEATURES_TO_UNHIGHLIGHT = "CLEAR_FEATURES_TO_UNHIGHLIGHT";
export const LOAD_IN_DISTRICTINGS = "LOAD_IN_DISTRICTINGS";
export const SET_VIEWING_DISTRICT_DETAILS = "SET_VIEWING_DISTRICT_DETAILS";
export const SET_CURRENT_TAB = "SET_CURRENT_TAB";
export const SET_MINIMIZED_MAP = "SET_MINIMIZED_MAP";
export const SET_VIEWPORT = "SET_VIEWPORT";
export const MINIMIZE_MAP = "MINIMIZE_MAP";
export const MAXIMIZE_MAP = "MAXIMIZE_MAP";
export const SET_STAT_SHOWCASED_DISTRICT_ID = "SET_STAT_SHOWCASED_DISTRICT";
export const RESTORE_DEFAULT_STATE_FOR_NEW_DISTRICTING =
  "RESTORE_DEFAULT_STATE_FOR_NEW_DISTRICTING";
export const SET_NEW_DISTRICTING_SELECTED = "SET_NEW_DISTRICTING_SELECTED";
export const SET_TENTATIVE_STATE = "SET_TENTATIVE_STATE";
export const SET_ENABLED_STATE_OF_CONSTRAINT =
  "SET_ENABLED_STATE_OF_CONSTRAINT";
export const SET_NUMBER_OF_DISTRICTINGS_AVAILABLE =
  "SET_NUMBER_OF_DISTRICTINGS_AVAILABLE";
export const UPDATE_ANALYSIS_DISTRICTINGS = "UPDATE_ANALYSIS_DISTRICTINGS";
export const LOAD_STATE_OUTLINES = "LOAD_STATE_OUTLINES";
export const TOGGLE_EXPANDED_SUMMARY = "TOGGLE_EXPANDED_SUMMARY";
export const RESET_EXPANDED_SUMMARIES = "RESET_EXPANDED_SUMMARIES";
export const SET_DISTRICTINGS_ARE_CONSTRAINED =
  "SET_DISTRICTINGS_ARE_CONSTRAINED";
export const LOAD_IN_JOBS = "LOAD_IN_JOBS";
export const SET_CURRENT_JOB = "SET_CURRENT_JOB";
export const POPULATE_PRECINCTS = "POPULATE_PRECINCTS";
export const POPULATE_COUNTIES = "POPULATE_COUNTIES";
export const POPULATE_CURRENT_DISTRICTING_GEOJSON =
  "POPULATE_CURRENT_DISTRICTING_GEOJSON";
export const POPULATE_CURRENT_DISTRICTING_SUMMARY =
  "POPULATE_CURRENT_DISTRICTING_SUMMARY";
export const RETURN_TO_STATE_SELECTION = "RETURN_TO_STATE_SELECTION"
export const UPDATE_BW_BOXES = "UPDATE_BW_BOXES"
export const UPDATE_BW_POINTS = "UPDATE_BW_POINTS"
export const UPDATE_SELECTED_TAGS = "UPDATE_SELECTED_TAGS"
export const UPDATE_BW_ENACTED = "UPDATE_BW_ENACTED"
export const UPDATE_JOB_LOADED = "UPDATE_JOB_LOADED"
export const UPDATE_ENACTED_GEOJSON = "UPDATE_ENACTED_GEOJSON"
