export const TOGGLE_PRECINCT_SWITCH = "TOGGLE_PRECINCT_SWITCH"
export const TOGGLE_DISTRICT_SWITCH = "TOGGLE_DISTRICT_SWITCH"
export const SET_TENTATIVE_DISTRICTING = "SET_TENTATIVE_DISTRICTING"
export const SET_CURRENT_DISTRICTING = "SET_CURRENT_DISTRICTING"